### ISSUE TITLE
Add to NPM

### ISSUE THREAD

**Issue by dnasir** [deerchao/dateformats#1]
I'd like to suggest that this package be added to NPM.

Keep up the awesome work!

**Comment by deerchao** [comment]
Now on npm.
https://www.npmjs.com/package/dateformats
New to use npm, you can check if there's anything wrong besides the no readme error.

**Comment by deerchao** [comment]
Added readme, closing this issue.

**Comment by dnasir** [comment]
@deerchao Awesome work! Thanks!
